name: .NET Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]
    runs-on: windows-latest
    env:
      Solution_Name: DoubleDashPlotter.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

      - name: Build the application
        run: msbuild $env:Solution_Name /t:Build /p:Configuration=${{ matrix.configuration }}

      # Instead of publishing via dotnet publish (which fails for .NET Framework projects),
      # copy the built outputs (including the .exe and its dependencies) from the bin folder.
      - name: Prepare Publish Folder
        run: |
          mkdir publish
          xcopy /E /I /Y DoubleDashPlotter/DoubleDashPlotter/bin/${{ matrix.configuration }} publish

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Outputs
          path: ./publish
