name: .NET Framework Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]
    runs-on: windows-latest
    env:
      # Replace with your solution name if different
      Solution_Name: DoubleDashPlotter.sln
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # Restore packages using MSBuild
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

      # Build the solution with shared compilation disabled
      - name: Build the application
        run: msbuild $env:Solution_Name /t:Build /p:Configuration=${{ matrix.configuration }} /p:UseSharedCompilation=false

      - name: Prepare Publish Folder
        run: |
          mkdir publish
          xcopy /E /I /Y "DoubleDashPlotter\DoubleDashPlotter\bin\${{ matrix.configuration }}" "publish"


      # Upload the publish folder as a build artifact (artifact name is tagged with the configuration)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Outputs-${{ matrix.configuration }}
          path: ./publish
