name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]
    runs-on: windows-latest
    env:
      # Replace with your solution name if different.
      Solution_Name: DoubleDashPlotter.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

      - name: Build the application
        run: msbuild $env:Solution_Name /t:Build /p:Configuration=${{ matrix.configuration }}

      # The publish step creates a folder with the .exe and all necessary files.
      # Adjust the project path (DoubleDashPlotter/DoubleDashPlotter.csproj) as needed.
      - name: Publish the application
        run: dotnet publish DoubleDashPlotter/DoubleDashPlotter.csproj --configuration ${{ matrix.configuration }} --output ./publish
        # If you need a self-contained executable, you can add:
        # --runtime win-x64 --self-contained true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Outputs
          path: ./publish
