name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: DoubleDashPlotter.sln

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore $env:Solution_Name

      - name: Build solution
        run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --no-restore

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Outputs
          path: bin/${{ matrix.configuration }}/
