name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: DoubleDashPlotter.sln  # Your solution file is in the repository root

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      # Optionally, list files for debugging to verify the output folder (uncomment if needed)
      - name: List build outputs
        run: dir /s /b

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Outputs
          path: bin/${{ matrix.configuration }}/
